stages:
  - build
  - test
  - docs


build-ubuntu:
  stage: build
  script:
    - echo "Build Stage"
    - cd extern/googletest
    - ls -al
    - cd googletest
    - ls -al
    # - mkdir -p build && cd build
    # - cmake ..
    # - make
  artifacts:
    expire_in: "1 hour"
    paths:
      - build/
  tags:
    - ubuntu

test-ubuntu:
  stage: test
  script:
    - echo "Test Stage"
    - ls -al
    - ./list_test
  needs:
    - build-ubuntu
  tags:
    - ubuntu

docs-ubuntu:
  stage: docs
  script:
    - echo "Docs Stage"
  needs:
    - test-ubuntu
  tags:
    - ubuntu
    