stages:
  - build
  - test
  - docs


build-ubuntu:
  stage: build
  script:
    - echo "Build Stage"
    - echo $CI_PROJECT_PATH
    - mkdir -p build && cd build
    - cmake ..
    - make
  tags:
    - ubuntu

test-ubuntu:
  stage: test
  script:
    - echo "Test Stage"
    - ls -al
    - ./list_test
  needs:
    - build-ubuntu
  tags:
    - ubuntu

docs-ubuntu:
  stage: docs
  script:
    - echo "Docs Stage"
  needs:
    - test-ubuntu
  tags:
    - ubuntu
    