stages:
  - build
  - test
  - docs


build-ubuntu:
  stage: build
  script:
    - echo "Build Stage"
    - echo $CI_PROJECT_PATH
    - ls -al
  tags:
    - ubuntu

test-ubuntu:
  stage: test
  script:
    - echo "Test Stage"
  needs:
    - build-ubuntu
  tags:
    - ubuntu

docs-ubuntu:
  stage: docs
  script:
    - echo "Docs Stage"
  needs:
    - test-ubuntu
  tags:
    - ubuntu
    